# Generated by Django 5.0.6 on 2025-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='total_donet_amount',
            field=models.FloatField(default=0),
        ),
    ]
