# Generated by Django 5.0.6 on 2025-01-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
