# Generated by Django 5.0.6 on 2025-01-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
