# Generated by Django 5.0.6 on 2025-01-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
