# Generated by Django 5.0.6 on 2025-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campain',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='campain',
            name='title',
        ),
        migrations.AddField(
            model_name='campain',
            name='campain_slug',
            field=models.SlugField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='campain',
            name='campain_title',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
