# Generated by Django 5.0.6 on 2025-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain', '0002_remove_campain_slug_remove_campain_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='campain_slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campain',
            name='campain_title',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
