# Generated by Django 5.0.6 on 2025-01-20 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_is_active'),
        ('campain', '0003_alter_campain_campain_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campain',
            name='donar',
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
    ]
