# Generated by Django 5.0.6 on 2025-01-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_is_active'),
        ('campain', '0004_remove_campain_donar_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='campain.campain'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='user',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.useraccount'),
        ),
    ]
