# Generated by Django 5.1.5 on 2025-01-31 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain', '0006_alter_campain_campain_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campain.campain'),
        ),
    ]
