# Generated by Django 5.0.6 on 2025-01-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_slug', models.SlugField(max_length=55)),
                ('category_image', models.ImageField(null=True, upload_to='./media/post_image/')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_slug', models.SlugField(max_length=255)),
                ('post_image', models.ImageField(upload_to='./media/post_image/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blogs.postcategorymodel')),
            ],
        ),
    ]
