# Generated by Django 5.0.6 on 2025-01-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_description',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='postcategorymodel',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='./media/post_image/'),
        ),
    ]
