# Generated by Django 5.0.6 on 2025-01-16 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_is_active'),
        ('blogs', '0002_postmodel_post_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Commernts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commenter', models.ManyToManyField(to='account.useraccount')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.postmodel')),
            ],
        ),
    ]
