# Generated by Django 5.0.6 on 2025-01-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_is_active'),
        ('blogs', '0003_post_commernts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_commernts',
            name='commenter',
        ),
        migrations.AddField(
            model_name='post_commernts',
            name='commenter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.useraccount'),
        ),
    ]
