# Generated by Django 5.0.6 on 2025-01-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'About_us'},
        ),
    ]
