# Generated by Django 5.0.6 on 2025-01-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_us_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About Us'},
        ),
    ]
